### ISSUE TITLE
[MSHARED-167] dependency:tree omits batik-js

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-tree#62]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** opened **[MSHARED-167](https://issues.apache.org/jira/browse/MSHARED-167?redirect=false)** and commented

(Not sure what the right place to file this is. `maven-dependency-tree 1.2` gives `MNG` as the JIRA component by inheritance.)

`mvn dependency:tree` on the attached project lists `batik-script` by way of `batik-bridge` as expected, but then fails to show `batik-js` as a dependency of that. If you list `batik-script` as a direct dependency, `batik-js` is correctly shown.

Possibly related is that Maven 2.2.1 also fails to find `batik-js` in `MavenProject.getRuntimeArtifacts`, so `clean package` fails, whereas this works fine under Maven 3.0. Yet just running the dependency plugin under M3 does not suffice to pick up this fix, wherever it was - MNG-4690?

Although the Batik JARs are built from an odd source tree, the artifacts as present in the local repository look normal enough; all of the dependencies involved are simple compile scope without exclusions etc.

Marking "major" since this seems to cause MNBMODULE-102 (producing build errors for certain projects); also I have noticed that the dependency graph feature in the NB IDE omits `batik-js`, and there may be other user-visible effects of this bug.

---

**Affects:** maven-dependency-tree-1.2

**Attachments:**
- [test_test-dependency-tree_jar_1.0-SNAPSHOT_101018-185145.zip](https://issues.apache.org/jira/secure/attachment/12719144/test_test-dependency-tree_jar_1.0-SNAPSHOT_101018-185145.zip) (_1.71 kB_)

**Issue Links:**
- [MDEP-662](https://issues.apache.org/jira/browse/MDEP-662) Re-Add Dependency Tree Verbose

- [MPIR-237](https://issues.apache.org/jira/browse/MPIR-237) Unexpected download
 (_**"is depended upon by"**_)
- [MDEP-339](https://issues.apache.org/jira/browse/MDEP-339) tree mojo doesn't work consistently with maven3
 (_**"is depended upon by"**_)
- [MENFORCER-140](https://issues.apache.org/jira/browse/MENFORCER-140) DependencyConvergence: upgrade maven-dependency-tree dependency to 2.0 for better Maven 3 support
 (_**"is depended upon by"**_)

1 votes, 7 watchers

**Comment by jira-importer** [comment]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** commented

I see. Should maven-dependency-tree then be considered fully deprecated? If so, is there some plan to release a fixed maven-dependency-plugin; and is there some documentation on which API in Maven core (or Aether) should be used in place of the deprecated component?

**Comment by jira-importer** [comment]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** commented

The above tree seems to be printed by:

```
at org.apache.maven.project.DefaultProjectDependenciesResolver$GraphLogger.visitEnter(DefaultProjectDependenciesResolver.java:223)
at org.sonatype.aether.impl.internal.GraphEdge.accept(GraphEdge.java:173)
at org.sonatype.aether.impl.internal.GraphEdge.accept(GraphEdge.java:177)
at org.sonatype.aether.impl.internal.GraphEdge.accept(GraphEdge.java:177)
at org.sonatype.aether.impl.internal.GraphEdge.accept(GraphEdge.java:177)
at org.sonatype.aether.impl.internal.GraphEdge.accept(GraphEdge.java:177)
at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:145)
```

**Comment by jira-importer** [comment]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** commented

Possibly related to MNG-4982?

**Comment by jira-importer** [comment]
**[David Tombs](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dgtombs)** commented

This issue just caused me some grief. Could this discrepancy between dependency:tree and the actual tree used possibly be documented in the dependency:tree docs?

**Comment by jira-importer** [comment]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** commented

I do not have commit privileges, so:

```
Index: src/main/java/org/apache/maven/plugin/dependency/TreeMojo.java
===================================================================
--- src/main/java/org/apache/maven/plugin/dependency/TreeMojo.java	(revision 1183422)
+++ src/main/java/org/apache/maven/plugin/dependency/TreeMojo.java	(working copy)
@@ -65,7 +65,7 @@
 
 /**
  * Displays the dependency tree for this project.
- *
+ * Beware that due to <a href="https://jira.codehaus.org/browse/MSHARED-167">MSHARED-167</a> the result may be incorrect in obscure cases.
  * @author <a href="mailto:markhobson@gmail.com">Mark Hobson</a>
  * @version $Id$
  * @since 2.0-alpha-5
```

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

new DependencyGraphBuilder component created in [r1348663](http://svn.apache.org/viewvc?rev=1348663&view=rev)

this component has a Maven 2 implementation using "usual" DependencyTreeBuilder and a Maven 3 implementation using Maven 3 with Aether
Default implementation detects current Maven version and automatically switches between the 2

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

IT added in [r1469697](http://svn.apache.org/r1469697): clearly shows how M2 has wrong resolution where M3 has a fixed one

**Comment by jira-importer** [comment]
**[Olof Larsson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olof%20larsson)** commented

I just added this related ticket with a completion bounty:
https://issues.apache.org/jira/browse/MDEP-662
